name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      run: sudo apt-get -y install cmake

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_PREFIX_PATH=${{github.workspace}}/lib/cmake/SDL2 -DSDL2_TTF_DIR=${{github.workspace}}/lib/cmake/SDL2_ttf
      
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Run Tests
      run: ${{github.workspace}}/build/run_tests

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ${{github.workspace}}/build/test-results
