name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: List Files in Working Directory
      run: ls -R $GITHUB_WORKSPACE
    - name: Install SDL2, SDL2_image, and SDL2_ttf
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev
    - name: Build and run tests
      run: |
        make autotest
        ./run_tests
