name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Debug Info
        run: |
          echo "Current directory: $PWD"
          echo "Contents of the 'lib' directory:"
          ls -R lib
          echo "Contents of the 'include' directory:"
          ls -R include
      - name: Install SDL2, SDL2_image, and SDL2_ttf
        run: |
          brew update
          brew install sdl2 sdl2_image sdl2_ttf
      - name: Build and run tests
        run: |
          make autotest
          ./run_tests
