name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      run: sudo apt-get -y install cmake

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake -DSDL2_LIBRARY=../lib/libSDL2.dylib -DSDL2_TTF_LIBRARY=../lib/libSDL2_ttf.dylib -DSDL2_IMAGE_LIBRARY=../lib/libSDL2_image.dylib ..
        make
        ./run_tests
